version: '3'
services:
  db:
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'user@%'
      MYSQL_PASS: 'pass'
      MYSQL_DATABASE: 'tg_bot'
      MYSQL_ROOT_HOST: '%' 
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
  app:
    restart: always
    environment: 
      PORT: ${PORT}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXPOSE}:${PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ./wait-for-it.sh -t 90 db:3306 -- node ./bin/server.js
    depends_on: 
        - db
volumes:
  node_modules:
