version: '3'
services:
  db:
    container_name: mariadb
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'user@%'
      MYSQL_PASS: 'pass'
      MYSQL_DATABASE: 'tg_bot'
      MYSQL_ROOT_HOST: '%' 
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
  app:
    container_name: bot
    restart: always
    environment: 
      - PORT: ${PORT}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXPOSE}:${PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ./wait-for-it.sh -t 90 mariadb:3306 -- node ./bin/server.js
    depends_on: 
        - db
    healthcheck:
      test: ["CMD", "curl -f http://localhost:$PORT/healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  node_modules:
